export default function translate(text: string) {
    return text;
}

[
    translate('saved.'),
    translate('wood'),
    translate('builder'),
    translate('teeth'),
    translate('meat'),
    translate('fur'),
    translate('alien alloy'),
    translate('bullets'),
    translate('charm'),
    translate('leather'),
    translate('iron'),
    translate('steel'),
    translate('coal'),
    translate('sulphur'),
    translate('energy cell'),
    translate('torch'),
    translate('medicine'),
    translate('hunter'),
    translate('trapper'),
    translate('tanner'),
    translate('grenade'),
    translate('bolas'),
    translate('bayonet'),
    translate('charcutier'),
    translate('iron miner'),
    translate('iron mine'),
    translate('coal miner'),
    translate('coal mine'),
    translate('sulphur miner'),
    translate('sulphur mine'),
    translate('armourer'),
    translate('steelworker'),
    translate('bait'),
    translate('cured meat'),
    translate('scales'),
    translate('compass'),
    translate('laser rifle'),
    translate('gatherer'),
    translate('cloth'),
    translate('scales'),
    translate('cured meat'),
    translate('thieves'),
    translate('baited trap'),
    translate('east'),
    translate('west'),
    translate('north'),
    translate('south'),
    translate('northeast'),
    translate('northwest'),
    translate('southeast'),
    translate('southwest'),
    translate('forest'),
    translate('village'),
    translate('A Lonely Hut'),
    translate('A Tiny Village'),
    translate('A Modest Village'),
    translate('A Large Village'),
    translate('A Raucous Village'),
    translate('miss'),
    translate('stunned'),
    translate('loot'),
    translate('bag'),
    translate('Buildings'),
    translate('income')
];